server:
 port: 8882
 servlet:
  context-path: /gradletest
logging:
 level:
  com.stt.gradletest : debug
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  username: root
  password: root
mybatis:
 mapper-locations: classpath:mappers/*.xml


ID: 20190226001
NAME: tom
AGE: 25
SEX: man
CONTENT: "我叫${NAME},我${AGE}岁,我是个${SEX},我的编号是${ID}"

custtest:
 id: 20190226002
 code: 20190225002
 name: jetty
 age: 26
 sex: woman
 address: "花神大道86号"
 content: "我叫${cust.name},我${cust.age}岁,我是个${cust.sex},我的编号是${cust.id}"