spring:
  application:
    name: neuMall-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/neusoftmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 39.106.45.82
    port: 6379
    password: xiaobai
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
eureka:
  client:
    service-url:
      dafaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8081
mybatis:
  #指定全局配置文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.neusoft.admin : debug   # 打印sql

rootId: 0






