spring:
  application:
    name: neuMall-gateway
  #配置redis
  redis:
    host: 39.106.45.82
    port: 6379
    password: xiaobai
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
eureka:
  client:
    service-url:
      dafaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8080
logging:
  level:
    com.neusoft: debug
zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: neuMall-admin
    mall:
      path: /mall/**
      serviceId: neuMall-mall


excludePath:






